version: '3.9'

networks:
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

  dmz:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1

  wireless:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1

services:
  db:
    image: mysql
    container_name: synapsetech-mysql-db
    networks:
      - lan
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysqldata:/var/lib/mysql

  app:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synapsetech-web
    networks:
      - lan
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./run.sh:/app/run.sh
    depends_on:
      - db
    command: bash run.sh

  apache:
    image: apache
    build:
      context: apache/
      dockerfile: Dockerfile
    container_name: synapsetech-apache
    networks:
      - dmz
      - lan
    depends_on:
      - app 

  firewall:
    image: shorewall
    build: 
      context: firewall/
      dockerfile: Dockerfile
    container_name: synapsetech-firewall   
    networks:
      - lan
      - dmz
      - wireless
    command: tail -f /dev/null   

volumes:
  mysqldata:
