version: '3'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysqldata:/var/lib/mysql
  app:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./run.sh:/app/run.sh
    depends_on:
      - db
    command: bash

volumes:
  mysqldata: