version: '3.9'

networks:
  synapsetech:
    driver: bridge
    name: synapsetech
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/8
          gateway: 10.0.0.1


services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    container_name: synapsetech-mysql-db
    networks:
      synapsetech:
        ipv4_address: 10.0.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysqldata:/var/lib/mysql
  app:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: synapsetech-web
    networks:
      synapsetech:
        ipv4_address: 10.0.0.3
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./run.sh:/app/run.sh
    depends_on:
      - db
    command: bash run.sh
  apache:
    image: apache
    build:
      context: apache/
      dockerfile: Dockerfile
    container_name: synapsetech-apache
    networks:
      synapsetech:
        ipv4_address: 10.0.0.4 
    depends_on:
      - app  

volumes:
  mysqldata: