version: '3.9'

networks:
  lan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

  dmz:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1

  wireless:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1

services:
  db:
    image: mysql:5
    container_name: synapsetech-mysql-db
    networks:
      lan:
        ipv4_address: 10.0.0.5
    ports:
      - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

  app:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synapsetech-web
    networks:
      lan:
        ipv4_address: 10.0.0.3
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./run.sh:/app/run.sh
    depends_on:
      - db
    command: bash run.sh

  apache:
    image: apache
    build:
      context: apache/
      dockerfile: Dockerfile
    container_name: synapsetech-apache
    networks:
      lan:
        ipv4_address: 10.0.0.10
      dmz:
        ipv4_address: 172.16.0.2  
    depends_on:
      - app 

  firewall:
    image: firewall
    build: 
      context: firewall/
      dockerfile: Dockerfile
    container_name: synapsetech-firewall
    cap_add:
      - NET_ADMIN   
    networks:
      lan:
        ipv4_address: 10.0.0.4
      dmz:
        ipv4_address: 172.16.0.3
      wireless:
        ipv4_address: 192.168.0.2  
    command: tail -f /dev/null


  client:
    image: ubuntu
    container_name: synapsetech-client    
    networks:
      - lan
    command: tail -f /dev/null

  kali:
    image: hackear
    build: 
      context: kali/
      dockerfile: Dockerfile
    container_name: synapsetech-kali
    cap_add:
      - NET_ADMIN  
    networks:
      lan:
        ipv4_address: 10.0.0.100
      dmz:
        ipv4_address: 172.16.0.100    
    command: tail -f /dev/null
